plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springAiVersion', '1.0.0-M6')
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Spring AI 의존성
    implementation 'org.springframework.ai:spring-ai-openai-spring-boot-starter'

    // Qdrant Vector DB 의존성
    implementation 'org.springframework.ai:spring-ai-qdrant-store-spring-boot-starter'

    // 2. PDF 및 다양한 문서에서 텍스트를 추출하기 위한 Tika 리더
    implementation 'org.springframework.ai:spring-ai-tika-document-reader'

    // PDF 처리 라이브러리
//    implementation 'org.apache.pdfbox:pdfbox:2.0.27'

    // Swagger/OpenAPI 의존성
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'

    // 테스트 의존성
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' } // 반드시 추가!
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
